### ISSUE TITLE
Confusion about readme's 'Converting other Circuits' step

### ISSUE THREAD

**Issue by jaimiosyncrasy** [GRIDAPPSD/CIMHub#21]
One of the steps says 'In the example.sh file, you have to replace the -s parameter with a correct one for your new circuit. For example, __DFBF372D-4291-49EF-ACCA-53DAFDE0338F should be changed to a new value. The correct value will be found on line 1 of the generated *UUIDS.dat file for your new circuit.'

How do I generate this .dat file? What do I run?

**Comment by temcdrm** [comment]
Fixed by https://github.com/GRIDAPPSD/CIMHub/commit/77981ad43ede4ee2655654d3a19661122baeb6a4
