### ISSUE TITLE
Missing triplex loads in CIM to GLM conversion

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/CIMHub#29]
Venkat is converting a feeder model with multiple triplex nodes connected to a single parent. These loads are present in the CIM XML file and converted base.dss file, but are missing from the base.glm file

There are three loads showing up correctly in the Blazegraph SPARQL query:

![image](https://user-images.githubusercontent.com/19935503/162095015-8e883ae0-5d82-422e-ba0f-18641c40a12e.png)

The exported GLM file using either the CIMHub py script or the simulation start message model_base.glm file only reports one of the three loads with an apparent power as the sum of all three nodes

![image](https://user-images.githubusercontent.com/19935503/162095491-909af4f0-6700-460a-8a3a-1b7960828b04.png)

![image](https://user-images.githubusercontent.com/19935503/162095943-5ec2d55b-d2a8-4b84-99b9-f10a2dc71801.png)

**Comment by temcdrm** [comment]
This behavior is by design, because of the grandchild limitation on parenting of node objects in GridLAB-D.  With the names blacked out, I can't tell whether this can be worked around in your example.  Are you able to run a small version of this model in GridLAB-D?

**Comment by temcdrm** [comment]
Please re-characterize as a feature request. This model can be fixed by creating separate triplex_line components between each transformer and the house load, as they are in the actual system.

**Comment by AAndersn** [comment]
Closing this issue as it is related to the modeling of the feeder, and not related to CIMHub. 
Loads in the real world will be connected by separate triplex lines, and should be modeled that way.
There does exist a use case for separate EnergyConsumer objects for individual types of loads, but CIM currently does not support associations between EnergyConsumer objects and appliance / house objects.

**Comment by AAndersn** [comment]
Will reopen if a use case emerges that needs separate modeling of EnergyConsumer objects inside a single house
