### ISSUE TITLE
Fault object in 9500 node GLM export

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/CIMHub#30]
@kevinpschneider and Jing have identified a fault object in the base GLM export. This object seems to be giving them convergence errors.

I have not run into the same issue when solving the same file, but had a similar problem for the fault_check object in the SDGE feeder.

```
object fault_check {
	name base_fault_check_object;
	check_mode ONCHANGE;
	strictly_radial false;
	eventgen_object testgendev;
	grid_association true;
}
object eventgen {
	name testgendev;
	fault_type "DLG-X";
	manual_outages "m1209-dies1,2100-01-01 00:00:05,2100-01-01 00:00:30";
```

**Comment by temcdrm** [comment]
This seems like a GridLAB-D issue, if it's causing a power flow convergence problem.  The manual_outage time never comes into play.  

The eventgen object is necessary for fault_check, which is necessary for the reliability module.  So, it can't be removed from the exported GridLAB-D file.

**Comment by temcdrm** [comment]
Per Jing's email, this was not actually causing trouble.  We need to keep eventgen and fault_check to be sure the GridLAB-D power flow will solve with disconnected subnetworks.
