### ISSUE TITLE
cyme2dss skipping 75% of bus coords

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/CIMHub#41]
cyme2dss is only writing 1/4 of bus coordinates from source sxst file

test model: nantucket

cyme original source file has 8108 nodes

opendss buscoords file has only 2027 lines

**Comment by JennyAppiah** [comment]
This issue has been fixed. It was caused by errors in CoordXmin, etc in the input json file created for the Cyme2DSS script. Thus, this wasn't a problem with Cyme2DSS file but with the cyme_sxst_to_cim.py file in CIM-Loader.
