### ISSUE TITLE
PSSE to CIM converter creating invalid association from WindGeneratingUnit to PowerElectronicsConnection 

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/CIMHub#42]
CIM converter for bus branch models is creating an invalid association between PowerElectronicsConnection and WindGeneratingUnit

https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/IEEE118_CIM.xml#L17977

Also, definition of PowerElectronicsUnit.minP and .maxP are an invalid attributes for WindGeneratingUnit

https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/IEEE118_CIM.xml#L17989

WindGeneratingUnit is a type of GeneratingUnit and associated with RotatingMachine / AsynchronousMachine if Type I/II

This should be defined defined instead as PowerElectronicsWindUnit if Type III/IV turbine connected through an inverter

...

![image](https://github.com/GRIDAPPSD/CIMHub/assets/19935503/efba8734-c725-4a44-a6b1-b3b3918a0b52)

**Comment by temcdrm** [comment]
https://github.com/Dewei-Wang-xx could handle this, starting at https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/raw/XMLtoCIM.py#L606

**Comment by temcdrm** [comment]
Fixed at https://github.com/GRIDAPPSD/CIMHub/commit/5284f4cfe38b49025067c1f2bc098392feb01d5f
