### ISSUE TITLE
Use of ConnectivityNodeContainer as an EquipmentContainer is invalid

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/CIMHub#43]
CIMhub is using ConnectivityNodeContainer as master parent class and writing Equipment.EquipmentContainer attributes to this class.

https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/IEEE118_CIM.xml#L7

This is invalid and violates the CIM UML. ConnectivityNodeContainer is the parent class of EquipmentContainer and does not inherit the child relationship of EquipmentContainer.Equipments.

ConnectivityNodeContainer needs to be replaced with EquipmentContainer in all BES code.

...

![image](https://github.com/GRIDAPPSD/CIMHub/assets/19935503/acd6da8e-a6ae-4bd0-a353-97f6751c44c9)

**Comment by temcdrm** [comment]
https://github.com/Dewei-Wang-xx could handle this, starting at https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/raw/XMLtoCIM.py#L68 and https://github.com/GRIDAPPSD/CIMHub/blob/feature/SETO/BES/raw/XMLtoCIM.py#L772

**Comment by temcdrm** [comment]
The same pattern applies to every distribution model. The Feeder inherits from EquipmentContainer.  ConnectivityNodes and Equipments both associate to the Feeder.

**Comment by temcdrm** [comment]
Fixed here https://github.com/GRIDAPPSD/CIMHub/commit/68d2c388640e016a25e6aff54e7cce792f2aedc3
