### ISSUE TITLE
Question on the README

### ISSUE THREAD

**Issue by OESNES** [GRIDAPPSD/CIMHub#47]
In the End User Instructions > Getting Started Example with Java/Python Option > "2. From another command prompt in the examples directory TBD" there is the **TBD** which indicates some instructions are missing.  

Is there some thing missing, if so what?  I ask because I am having issues converting the 123-node tutorial model.

**Comment by temcdrm** [comment]
Fixed here: https://github.com/GRIDAPPSD/CIMHub/commit/988cc49111bf2474838ac37cc1070b627a5b782e

**Comment by OESNES** [comment]
Thanks
